// Loading
export const LOAD_START = 'LOAD_START'
export const LOAD_END = 'LOAD_END'
export const LOAD_ERROR = 'LOAD_ERROR'

// Server
export const SERVER_INITIAL_LOAD = 'SERVER_INITIAL_LOAD'

// Nav steps
export const STEP_UPDATE = 'STEP_UPDATE'

// Orders 
export const ORDER_UPDATE_NAME = 'ORDER_UPDATE_NAME'
export const ORDER_UPDATE_COLOR = 'ORDER_UPDATE_COLOR'
export const ORDER_PLAYER_CREATE = 'ORDER_PLAYER_CREATE'
export const ORDER_PLAYER_UPDATE = 'ORDER_PLAYER_UPDATE'
export const ORDER_PLAYER_DELETE = 'ORDER_PLAYER_DELETE'

// Saving
export const SAVE_TOGGLE = 'SAVE_TOGGLE'
export const SAVE_COMMIT = 'SAVE_COMMIT'
export const SAVE_LOAD = 'SAVE_LOAD'

// Colors
export const COLORS_UPDATE_SEGMENT = 'COLORS_UPDATE_SEGMENT'
export const COLORS_CHANGE = 'COLORS_CHANGE'

// Decorations
export const DECORATION_CREATE = 'DECORATION_CREATE'
export const DECORATION_SELECT = 'DECORATION_SELECT'
export const DECORATION_UPDATE = 'DECORATION_UPDATE'
export const DECORATION_DELETE = 'DECORATION_DELETE'
export const DECORATION_MOVE = 'DECORATION_MOVE'

// Patterns
export const PATTERN_CHOOSE = 'PATTERN_CHOOSE'

// Styles
export const STYLES_LOAD = 'STYLES_LOAD'
export const STYLES_CHOOSE_SPORT = 'STYLES_CHOOSE_SPORT'
export const STYLES_CHOOSE_STYLE = 'STYLES_CHOOSE_STYLE'

// Designer
export const DESIGNER_COLORS_CHANGE = 'DESIGNER_COLORS_CHANGE'
export const DESIGNER_LOAD_DESIGN = 'DESIGNER_LOAD_DESIGN'
export const DESIGNER_INIT = 'DESIGNER_INIT'
export const DESIGNER_EXECUTE = 'DESIGNER_EXECUTE'
export const DESIGNER_CLEAR = 'DESIGNER_CLEAR'
export const DESIGNER_LOAD_START = 'DESIGNER_LOAD_START'
export const DESIGNER_LOAD_END = 'DESIGNER_LOAD_END'

// Notifications
export const NOTIFICATION_EMIT = 'NOTIFICATION_EMIT'
export const NOTIFICATION_REMOVE = 'NOTIFICATION_REMOVE'
